#! /bin/sh

if [ ! -f doc/RELEASE ];then
  ln phreeqc3-doc/RELEASE.TXT doc/RELEASE
fi

if [ ! -f doc/NOTICE ];then
  ln phreeqc3-doc/NOTICE.TXT doc/NOTICE
fi

if [ ! -f doc/phreeqc3.chm ];then
  svn export http://internalbrr.cr.usgs.gov/svn_GW/phreeqc3/trunk/HTMLversion/phreeqc3.chm doc/phreeqc3.chm
fi

exec autoreconf -fvi

