set(CTEST_BUILD_NAME "VS2008-x64-fortran")
set(CTEST_SITE "IGSKAHHWWSCHARL")

set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}")
set(CTEST_BINARY_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/_vs2008-64")
set(CTEST_CMAKE_GENERATOR "Visual Studio 9 2008 Win64")

# Build Fortran test (First build option can't have any beginning whitespace)
set(ADD_BUILD_OPTIONS "-DIPHREEQC_FORTRAN_TESTING:BOOL=ON")

# Build Shared Libraries
#set(ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DBUILD_SHARED_LIBS:BOOL=OFF")

# Build the testing tree
#set(ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DBUILD_TESTING:BOOL=ON")

# Enable Fortran module
#set(ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DIPHREEQC_ENABLE_MODULE:BOOL=ON")

CTEST_START("Experimental")
CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}"
                OPTIONS "${ADD_BUILD_OPTIONS}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_TEST(BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" TARGET PACKAGE)
###CTEST_SUBMIT()