# examples
# strings
##ex1.string <- paste(scan("../phreeqc3-examples/ex1", what="", sep="\n"), collapse="\n")
##ex2.string <- paste(scan("../phreeqc3-examples/ex2", what="", sep="\n"), collapse="\n")
##ex3.string <- paste(scan("../phreeqc3-examples/ex3", what="", sep="\n"), collapse="\n")
##ex4.string <- paste(scan("../phreeqc3-examples/ex4", what="", sep="\n"), collapse="\n")
##ex5.string <- paste(scan("../phreeqc3-examples/ex5", what="", sep="\n"), collapse="\n")
##ex6.string <- paste(scan("../phreeqc3-examples/ex6", what="", sep="\n"), collapse="\n")
##ex7.string <- paste(scan("../phreeqc3-examples/ex7", what="", sep="\n"), collapse="\n")
##ex8.string <- paste(scan("../phreeqc3-examples/ex8", what="", sep="\n"), collapse="\n")
##ex9.string <- paste(scan("../phreeqc3-examples/ex9", what="", sep="\n"), collapse="\n")
# lists
ex1   <- scan("../phreeqc3-examples/ex1", what="", sep="\n")
ex2   <- scan("../phreeqc3-examples/ex2", what="", sep="\n")
ex3   <- scan("../phreeqc3-examples/ex3", what="", sep="\n")
ex4   <- scan("../phreeqc3-examples/ex4", what="", sep="\n")
ex5   <- scan("../phreeqc3-examples/ex5", what="", sep="\n")
ex6   <- scan("../phreeqc3-examples/ex6", what="", sep="\n")
ex7   <- scan("../phreeqc3-examples/ex7", what="", sep="\n")
ex8   <- scan("../phreeqc3-examples/ex8", what="", sep="\n")
ex9   <- scan("../phreeqc3-examples/ex9", what="", sep="\n")
save(list = ls(all=TRUE), file="phreeqc/data/examples.RData")
rm(list = ls(all=TRUE))
