# examples
# strings
##ex1.string <- paste(scan("../phreeqc3-examples/ex1", what="", sep="\n"), collapse="\n")
##ex2.string <- paste(scan("../phreeqc3-examples/ex2", what="", sep="\n"), collapse="\n")
##ex3.string <- paste(scan("../phreeqc3-examples/ex3", what="", sep="\n"), collapse="\n")
##ex4.string <- paste(scan("../phreeqc3-examples/ex4", what="", sep="\n"), collapse="\n")
##ex5.string <- paste(scan("../phreeqc3-examples/ex5", what="", sep="\n"), collapse="\n")
##ex6.string <- paste(scan("../phreeqc3-examples/ex6", what="", sep="\n"), collapse="\n")
##ex7.string <- paste(scan("../phreeqc3-examples/ex7", what="", sep="\n"), collapse="\n")
##ex8.string <- paste(scan("../phreeqc3-examples/ex8", what="", sep="\n"), collapse="\n")
##ex9.string <- paste(scan("../phreeqc3-examples/ex9", what="", sep="\n"), collapse="\n")
# lists
ex1   <- scan("../phreeqc3-examples/ex1",   what="", sep="\n")
ex2   <- scan("../phreeqc3-examples/ex2",   what="", sep="\n")
ex3   <- scan("../phreeqc3-examples/ex3",   what="", sep="\n")
ex4   <- scan("../phreeqc3-examples/ex4",   what="", sep="\n")
ex5   <- scan("../phreeqc3-examples/ex5",   what="", sep="\n")
ex6   <- scan("../phreeqc3-examples/ex6",   what="", sep="\n")
ex7   <- scan("../phreeqc3-examples/ex7",   what="", sep="\n")
ex8   <- scan("../phreeqc3-examples/ex8",   what="", sep="\n")
ex9   <- scan("../phreeqc3-examples/ex9",   what="", sep="\n")
ex10  <- scan("../phreeqc3-examples/ex10",  what="", sep="\n")
ex11  <- scan("../phreeqc3-examples/ex11",  what="", sep="\n")
ex12  <- scan("../phreeqc3-examples/ex12",  what="", sep="\n")
ex13a <- scan("../phreeqc3-examples/ex13a", what="", sep="\n")
ex13b <- scan("../phreeqc3-examples/ex13b", what="", sep="\n")
ex13c <- scan("../phreeqc3-examples/ex13c", what="", sep="\n")
ex14  <- scan("../phreeqc3-examples/ex14",  what="", sep="\n")
ex15  <- scan("../phreeqc3-examples/ex15",  what="", sep="\n")
ex16  <- scan("../phreeqc3-examples/ex16",  what="", sep="\n")
ex17  <- scan("../phreeqc3-examples/ex17",  what="", sep="\n")
ex18  <- scan("../phreeqc3-examples/ex18",  what="", sep="\n")
ex19  <- scan("../phreeqc3-examples/ex19",  what="", sep="\n")
ex20a <- scan("../phreeqc3-examples/ex20a", what="", sep="\n")
ex20b <- scan("../phreeqc3-examples/ex20b", what="", sep="\n")
ex21  <- scan("ex21.ascii",                 what="", sep="\n")
ex22  <- scan("../phreeqc3-examples/ex22",  what="", sep="\n")

save(list = ls(all=TRUE), file="phreeqc/data/examples.rda")
rm(list = ls(all=TRUE))
