# databases
##Amm.dat.string       <- paste(scan("../database/Amm.dat",       what="", sep="\n"), collapse="\n")
##ColdChem.dat.string  <- paste(scan("../database/ColdChem.dat",  what="", sep="\n"), collapse="\n")
##iso.dat.string       <- paste(scan("../database/iso.dat",       what="", sep="\n"), collapse="\n")
##llnl.dat.string      <- paste(scan("../database/llnl.dat",      what="", sep="\n"), collapse="\n")
##minteq.dat.string    <- paste(scan("../database/minteq.dat",    what="", sep="\n"), collapse="\n")
##minteq.v4.dat.string <- paste(scan("../database/minteq.v4.dat", what="", sep="\n"), collapse="\n")
##pitzer.dat.string    <- paste(scan("../database/pitzer.dat",    what="", sep="\n"), collapse="\n")
##sit.dat.string       <- paste(scan("../database/sit.dat",       what="", sep="\n"), collapse="\n")
##phreeqc.dat.string   <- paste(scan("../database/phreeqc.dat",   what="", sep="\n"), collapse="\n")
##wateq4f.dat.string   <- paste(scan("../database/wateq4f.dat",   what="", sep="\n"), collapse="\n")
# lists
Amm.dat         <- scan("Amm.ascii",       what="", sep="\n")
ColdChem.dat    <- scan("ColdChem.ascii",  what="", sep="\n")
ex15.dat        <- scan("ex15.ascii",      what="", sep="\n")
iso.dat         <- scan("iso.ascii",       what="", sep="\n")
llnl.dat        <- scan("llnl.ascii",      what="", sep="\n")
minteq.dat      <- scan("minteq.ascii",    what="", sep="\n")
minteq.v4.dat   <- scan("minteq.v4.ascii", what="", sep="\n")
pitzer.dat      <- scan("pitzer.ascii",    what="", sep="\n")
sit.dat         <- scan("sit.ascii",       what="", sep="\n")
phreeqc.dat     <- scan("phreeqc.ascii",   what="", sep="\n")
wateq4f.dat     <- scan("wateq4f.ascii",   what="", sep="\n")
save(list = ls(all = TRUE), file = "phreeqc/data/databases.rda", compress = "xz")
rm(list = ls(all = TRUE))
