# databases
##Amm.dat.string       <- paste(scan("../database/Amm.dat",       what="", sep="\n"), collapse="\n")
##iso.dat.string       <- paste(scan("../database/iso.dat",       what="", sep="\n"), collapse="\n")
##llnl.dat.string      <- paste(scan("../database/llnl.dat",      what="", sep="\n"), collapse="\n")
##minteq.dat.string    <- paste(scan("../database/minteq.dat",    what="", sep="\n"), collapse="\n")
##minteq.v4.dat.string <- paste(scan("../database/minteq.v4.dat", what="", sep="\n"), collapse="\n")
##pitzer.dat.string    <- paste(scan("../database/pitzer.dat",    what="", sep="\n"), collapse="\n")
##sit.dat.string       <- paste(scan("../database/sit.dat",       what="", sep="\n"), collapse="\n")
##phreeqc.dat.string   <- paste(scan("../database/phreeqc.dat",   what="", sep="\n"), collapse="\n")
##wateq4f.dat.string   <- paste(scan("../database/wateq4f.dat",   what="", sep="\n"), collapse="\n")
# lists
Amm.dat         <- scan("../database/Amm.dat",       what="", sep="\n")
iso.dat         <- scan("../database/iso.dat",       what="", sep="\n")
llnl.dat        <- scan("../database/llnl.dat",      what="", sep="\n")
minteq.dat      <- scan("../database/minteq.dat",    what="", sep="\n")
minteq.v4.dat   <- scan("../database/minteq.v4.dat", what="", sep="\n")
pitzer.dat      <- scan("../database/pitzer.dat",    what="", sep="\n")
sit.dat         <- scan("../database/sit.dat",       what="", sep="\n")
phreeqc.dat     <- scan("../database/phreeqc.dat",   what="", sep="\n")
wateq4f.dat     <- scan("../database/wateq4f.dat",   what="", sep="\n")
save(list = ls(all=TRUE), file="phreeqc/data/databases.RData")
rm(list = ls(all=TRUE))
