DEST=phreeqc/src
SRC=../src/phreeqcpp
CP=cp -f

PSRC = \
	$(DEST)/advection.cpp \
	$(DEST)/basicsubs.cpp \
	$(DEST)/ChartHandler.cpp \
	$(DEST)/ChartHandler.h \
	$(DEST)/ChartObject.cpp \
	$(DEST)/ChartObject.h \
	$(DEST)/cl1.cpp \
	$(DEST)/cl1mp.cpp \
	$(DEST)/class_main.cpp \
	$(DEST)/CurveObject.cpp \
	$(DEST)/CurveObject.h \
	$(DEST)/cvdense.cpp \
	$(DEST)/cvdense.h \
	$(DEST)/cvode.cpp \
	$(DEST)/cvode.h \
	$(DEST)/cxxKinetics.cxx \
	$(DEST)/cxxKinetics.h \
	$(DEST)/cxxMix.cxx \
	$(DEST)/cxxMix.h \
	$(DEST)/dense.cpp \
	$(DEST)/dense.h \
	$(DEST)/dumper.cpp \
	$(DEST)/dumper.h \
	$(DEST)/dw.cpp \
	$(DEST)/Exchange.cxx \
	$(DEST)/Exchange.h \
	$(DEST)/ExchComp.cxx \
	$(DEST)/ExchComp.h \
	$(DEST)/GasComp.cxx \
	$(DEST)/GasComp.h \
	$(DEST)/gases.cpp \
	$(DEST)/GasPhase.cxx \
	$(DEST)/GasPhase.h \
	$(DEST)/global_structures.h \
	$(DEST)/input.cpp \
	$(DEST)/integrate.cpp \
	$(DEST)/inverse.cpp \
	$(DEST)/ISolution.cxx \
	$(DEST)/ISolution.h \
	$(DEST)/ISolutionComp.cxx \
	$(DEST)/ISolutionComp.h \
	$(DEST)/isotopes.cpp \
	$(DEST)/Keywords.cpp \
	$(DEST)/Keywords.h \
	$(DEST)/kinetics.cpp \
	$(DEST)/KineticsComp.cxx \
	$(DEST)/KineticsComp.h \
	$(DEST)/mainsubs.cpp \
	$(DEST)/model.cpp \
	$(DEST)/NA.h \
	$(DEST)/NameDouble.cxx \
	$(DEST)/NameDouble.h \
	$(DEST)/NumKeyword.cxx \
	$(DEST)/NumKeyword.h \
	$(DEST)/nvector.cpp \
	$(DEST)/nvector.h \
	$(DEST)/nvector_serial.cpp \
	$(DEST)/nvector_serial.h \
	$(DEST)/parse.cpp \
	$(DEST)/Parser.cxx \
	$(DEST)/Parser.h \
	$(DEST)/PBasic.cpp \
	$(DEST)/PBasic.h \
	$(DEST)/phqalloc.cpp \
	$(DEST)/phqalloc.h \
	$(DEST)/Phreeqc.cpp \
	$(DEST)/Phreeqc.h \
	$(DEST)/PHRQ_base.cxx \
	$(DEST)/PHRQ_base.h \
	$(DEST)/PHRQ_io.cpp \
	$(DEST)/PHRQ_io.h \
	$(DEST)/PHRQ_io_output.cpp \
	$(DEST)/phrqtype.h \
	$(DEST)/pitzer.cpp \
	$(DEST)/pitzer_structures.cpp \
	$(DEST)/PPassemblage.cxx \
	$(DEST)/PPassemblage.h \
	$(DEST)/PPassemblageComp.cxx \
	$(DEST)/PPassemblageComp.h \
	$(DEST)/prep.cpp \
	$(DEST)/Pressure.cxx \
	$(DEST)/Pressure.h \
	$(DEST)/print.cpp \
	$(DEST)/Reaction.cxx \
	$(DEST)/Reaction.h \
	$(DEST)/read.cpp \
	$(DEST)/ReadClass.cxx \
	$(DEST)/readtr.cpp \
	$(DEST)/runner.cpp \
	$(DEST)/runner.h \
	$(DEST)/SelectedOutput.cpp \
	$(DEST)/SelectedOutput.h \
	$(DEST)/sit.cpp \
	$(DEST)/smalldense.cpp \
	$(DEST)/smalldense.h \
	$(DEST)/Solution.cxx \
	$(DEST)/Solution.h \
	$(DEST)/SolutionIsotope.cxx \
	$(DEST)/SolutionIsotope.h \
	$(DEST)/spread.cpp \
	$(DEST)/SS.cxx \
	$(DEST)/SS.h \
	$(DEST)/SSassemblage.cxx \
	$(DEST)/SSassemblage.h \
	$(DEST)/SScomp.cxx \
	$(DEST)/SScomp.h \
	$(DEST)/step.cpp \
	$(DEST)/StorageBin.cxx \
	$(DEST)/StorageBin.h \
	$(DEST)/StorageBinList.cpp \
	$(DEST)/StorageBinList.h \
	$(DEST)/structures.cpp \
	$(DEST)/sundialsmath.cpp \
	$(DEST)/sundialsmath.h \
	$(DEST)/sundialstypes.h \
	$(DEST)/Surface.cxx \
	$(DEST)/Surface.h \
	$(DEST)/SurfaceCharge.cxx \
	$(DEST)/SurfaceCharge.h \
	$(DEST)/SurfaceComp.cxx \
	$(DEST)/SurfaceComp.h \
	$(DEST)/System.cxx \
	$(DEST)/System.h \
	$(DEST)/tally.cpp \
	$(DEST)/Temperature.cxx \
	$(DEST)/Temperature.h \
	$(DEST)/tidy.cpp \
	$(DEST)/transport.cpp \
	$(DEST)/Use.cpp \
	$(DEST)/Use.h \
	$(DEST)/UserPunch.cpp \
	$(DEST)/UserPunch.h \
	$(DEST)/utilities.cpp \
	$(DEST)/Utils.cxx \
	$(DEST)/Utils.h


all: $(PSRC)

$(DEST)/advection.cpp : $(SRC)/advection.cpp
	$(CP) $< $@

$(DEST)/basicsubs.cpp : $(SRC)/basicsubs.cpp
	$(CP) $< $@

$(DEST)/ChartHandler.cpp : $(SRC)/ChartHandler.cpp
	$(CP) $< $@

$(DEST)/ChartHandler.h : $(SRC)/ChartHandler.h
	$(CP) $< $@

$(DEST)/ChartObject.cpp : $(SRC)/ChartObject.cpp
	$(CP) $< $@

$(DEST)/ChartObject.h : $(SRC)/ChartObject.h
	$(CP) $< $@

$(DEST)/cl1.cpp : $(SRC)/cl1.cpp
	$(CP) $< $@

$(DEST)/cl1mp.cpp : $(SRC)/cl1mp.cpp
	$(CP) $< $@

$(DEST)/class_main.cpp : $(SRC)/class_main.cpp
	$(CP) $< $@

$(DEST)/CurveObject.cpp : $(SRC)/CurveObject.cpp
	$(CP) $< $@

$(DEST)/CurveObject.h : $(SRC)/CurveObject.h
	$(CP) $< $@

$(DEST)/cvdense.cpp : $(SRC)/cvdense.cpp
	$(CP) $< $@

$(DEST)/cvdense.h : $(SRC)/cvdense.h
	$(CP) $< $@

$(DEST)/cvode.cpp : $(SRC)/cvode.cpp
	$(CP) $< $@

$(DEST)/cvode.h : $(SRC)/cvode.h
	$(CP) $< $@

$(DEST)/cxxKinetics.cxx : $(SRC)/cxxKinetics.cxx
	$(CP) $< $@

$(DEST)/cxxKinetics.h : $(SRC)/cxxKinetics.h
	$(CP) $< $@

$(DEST)/cxxMix.cxx : $(SRC)/cxxMix.cxx
	$(CP) $< $@

$(DEST)/cxxMix.h : $(SRC)/cxxMix.h
	$(CP) $< $@

$(DEST)/dense.cpp : $(SRC)/dense.cpp
	$(CP) $< $@

$(DEST)/dense.h : $(SRC)/dense.h
	$(CP) $< $@

$(DEST)/dumper.cpp : $(SRC)/dumper.cpp
	$(CP) $< $@

$(DEST)/dumper.h : $(SRC)/dumper.h
	$(CP) $< $@

$(DEST)/dw.cpp : $(SRC)/dw.cpp
	$(CP) $< $@

$(DEST)/Exchange.cxx : $(SRC)/Exchange.cxx
	$(CP) $< $@

$(DEST)/Exchange.h : $(SRC)/Exchange.h
	$(CP) $< $@

$(DEST)/ExchComp.cxx : $(SRC)/ExchComp.cxx
	$(CP) $< $@

$(DEST)/ExchComp.h : $(SRC)/ExchComp.h
	$(CP) $< $@

$(DEST)/GasComp.cxx : $(SRC)/GasComp.cxx
	$(CP) $< $@

$(DEST)/GasComp.h : $(SRC)/GasComp.h
	$(CP) $< $@

$(DEST)/gases.cpp : $(SRC)/gases.cpp
	$(CP) $< $@

$(DEST)/GasPhase.cxx : $(SRC)/GasPhase.cxx
	$(CP) $< $@

$(DEST)/GasPhase.h : $(SRC)/GasPhase.h
	$(CP) $< $@

$(DEST)/global_structures.h : $(SRC)/global_structures.h
	$(CP) $< $@

$(DEST)/input.cpp : $(SRC)/input.cpp
	$(CP) $< $@

$(DEST)/integrate.cpp : $(SRC)/integrate.cpp
	$(CP) $< $@

$(DEST)/inverse.cpp : $(SRC)/inverse.cpp
	$(CP) $< $@

$(DEST)/ISolution.cxx : $(SRC)/ISolution.cxx
	$(CP) $< $@

$(DEST)/ISolution.h : $(SRC)/ISolution.h
	$(CP) $< $@

$(DEST)/ISolutionComp.cxx : $(SRC)/ISolutionComp.cxx
	$(CP) $< $@

$(DEST)/ISolutionComp.h : $(SRC)/ISolutionComp.h
	$(CP) $< $@

$(DEST)/isotopes.cpp : $(SRC)/isotopes.cpp
	$(CP) $< $@

$(DEST)/Keywords.cpp : $(SRC)/Keywords.cpp
	$(CP) $< $@

$(DEST)/Keywords.h : $(SRC)/Keywords.h
	$(CP) $< $@

$(DEST)/kinetics.cpp : $(SRC)/kinetics.cpp
	$(CP) $< $@

$(DEST)/KineticsComp.cxx : $(SRC)/KineticsComp.cxx
	$(CP) $< $@

$(DEST)/KineticsComp.h : $(SRC)/KineticsComp.h
	$(CP) $< $@

$(DEST)/mainsubs.cpp : $(SRC)/mainsubs.cpp
	$(CP) $< $@

$(DEST)/model.cpp : $(SRC)/model.cpp
	$(CP) $< $@

$(DEST)/NA.h : $(SRC)/NA.h
	$(CP) $< $@

$(DEST)/NameDouble.cxx : $(SRC)/NameDouble.cxx
	$(CP) $< $@

$(DEST)/NameDouble.h : $(SRC)/NameDouble.h
	$(CP) $< $@

$(DEST)/NumKeyword.cxx : $(SRC)/NumKeyword.cxx
	$(CP) $< $@

$(DEST)/NumKeyword.h : $(SRC)/NumKeyword.h
	$(CP) $< $@

$(DEST)/nvector.cpp : $(SRC)/nvector.cpp
	$(CP) $< $@

$(DEST)/nvector.h : $(SRC)/nvector.h
	$(CP) $< $@

$(DEST)/nvector_serial.cpp : $(SRC)/nvector_serial.cpp
	$(CP) $< $@

$(DEST)/nvector_serial.h : $(SRC)/nvector_serial.h
	$(CP) $< $@

$(DEST)/parse.cpp : $(SRC)/parse.cpp
	$(CP) $< $@

$(DEST)/Parser.cxx : $(SRC)/Parser.cxx
	$(CP) $< $@

$(DEST)/Parser.h : $(SRC)/Parser.h
	$(CP) $< $@

$(DEST)/PBasic.cpp : $(SRC)/PBasic.cpp
	$(CP) $< $@

$(DEST)/PBasic.h : $(SRC)/PBasic.h
	$(CP) $< $@

$(DEST)/phqalloc.cpp : $(SRC)/phqalloc.cpp
	$(CP) $< $@

$(DEST)/phqalloc.h : $(SRC)/phqalloc.h
	$(CP) $< $@

$(DEST)/Phreeqc.cpp : $(SRC)/Phreeqc.cpp
	$(CP) $< $@

$(DEST)/Phreeqc.h : $(SRC)/Phreeqc.h
	$(CP) $< $@

$(DEST)/PHRQ_base.cxx : $(SRC)/PHRQ_base.cxx
	$(CP) $< $@

$(DEST)/PHRQ_base.h : $(SRC)/PHRQ_base.h
	$(CP) $< $@

$(DEST)/PHRQ_io.cpp : $(SRC)/PHRQ_io.cpp
	$(CP) $< $@

$(DEST)/PHRQ_io.h : $(SRC)/PHRQ_io.h
	$(CP) $< $@

$(DEST)/PHRQ_io_output.cpp : $(SRC)/PHRQ_io_output.cpp
	$(CP) $< $@

$(DEST)/phrqtype.h : $(SRC)/phrqtype.h
	$(CP) $< $@

$(DEST)/pitzer.cpp : $(SRC)/pitzer.cpp
	$(CP) $< $@

$(DEST)/pitzer_structures.cpp : $(SRC)/pitzer_structures.cpp
	$(CP) $< $@

$(DEST)/PPassemblage.cxx : $(SRC)/PPassemblage.cxx
	$(CP) $< $@

$(DEST)/PPassemblage.h : $(SRC)/PPassemblage.h
	$(CP) $< $@

$(DEST)/PPassemblageComp.cxx : $(SRC)/PPassemblageComp.cxx
	$(CP) $< $@

$(DEST)/PPassemblageComp.h : $(SRC)/PPassemblageComp.h
	$(CP) $< $@

$(DEST)/prep.cpp : $(SRC)/prep.cpp
	$(CP) $< $@

$(DEST)/Pressure.cxx : $(SRC)/Pressure.cxx
	$(CP) $< $@

$(DEST)/Pressure.h : $(SRC)/Pressure.h
	$(CP) $< $@

$(DEST)/print.cpp : $(SRC)/print.cpp
	$(CP) $< $@

$(DEST)/Reaction.cxx : $(SRC)/Reaction.cxx
	$(CP) $< $@

$(DEST)/Reaction.h : $(SRC)/Reaction.h
	$(CP) $< $@

$(DEST)/read.cpp : $(SRC)/read.cpp
	$(CP) $< $@

$(DEST)/ReadClass.cxx : $(SRC)/ReadClass.cxx
	$(CP) $< $@

$(DEST)/readtr.cpp : $(SRC)/readtr.cpp
	$(CP) $< $@

$(DEST)/runner.cpp : $(SRC)/runner.cpp
	$(CP) $< $@

$(DEST)/runner.h : $(SRC)/runner.h
	$(CP) $< $@

$(DEST)/SelectedOutput.cpp : $(SRC)/SelectedOutput.cpp
	$(CP) $< $@

$(DEST)/SelectedOutput.h : $(SRC)/SelectedOutput.h
	$(CP) $< $@

$(DEST)/sit.cpp : $(SRC)/sit.cpp
	$(CP) $< $@

$(DEST)/smalldense.cpp : $(SRC)/smalldense.cpp
	$(CP) $< $@

$(DEST)/smalldense.h : $(SRC)/smalldense.h
	$(CP) $< $@

$(DEST)/Solution.cxx : $(SRC)/Solution.cxx
	$(CP) $< $@

$(DEST)/Solution.h : $(SRC)/Solution.h
	$(CP) $< $@

$(DEST)/SolutionIsotope.cxx : $(SRC)/SolutionIsotope.cxx
	$(CP) $< $@

$(DEST)/SolutionIsotope.h : $(SRC)/SolutionIsotope.h
	$(CP) $< $@

$(DEST)/spread.cpp : $(SRC)/spread.cpp
	$(CP) $< $@

$(DEST)/SS.cxx : $(SRC)/SS.cxx
	$(CP) $< $@

$(DEST)/SS.h : $(SRC)/SS.h
	$(CP) $< $@

$(DEST)/SSassemblage.cxx : $(SRC)/SSassemblage.cxx
	$(CP) $< $@

$(DEST)/SSassemblage.h : $(SRC)/SSassemblage.h
	$(CP) $< $@

$(DEST)/SScomp.cxx : $(SRC)/SScomp.cxx
	$(CP) $< $@

$(DEST)/SScomp.h : $(SRC)/SScomp.h
	$(CP) $< $@

$(DEST)/step.cpp : $(SRC)/step.cpp
	$(CP) $< $@

$(DEST)/StorageBin.cxx : $(SRC)/StorageBin.cxx
	$(CP) $< $@

$(DEST)/StorageBin.h : $(SRC)/StorageBin.h
	$(CP) $< $@

$(DEST)/StorageBinList.cpp : $(SRC)/StorageBinList.cpp
	$(CP) $< $@

$(DEST)/StorageBinList.h : $(SRC)/StorageBinList.h
	$(CP) $< $@

$(DEST)/structures.cpp : $(SRC)/structures.cpp
	$(CP) $< $@

$(DEST)/sundialsmath.cpp : $(SRC)/sundialsmath.cpp
	$(CP) $< $@

$(DEST)/sundialsmath.h : $(SRC)/sundialsmath.h
	$(CP) $< $@

$(DEST)/sundialstypes.h : $(SRC)/sundialstypes.h
	$(CP) $< $@

$(DEST)/Surface.cxx : $(SRC)/Surface.cxx
	$(CP) $< $@

$(DEST)/Surface.h : $(SRC)/Surface.h
	$(CP) $< $@

$(DEST)/SurfaceCharge.cxx : $(SRC)/SurfaceCharge.cxx
	$(CP) $< $@

$(DEST)/SurfaceCharge.h : $(SRC)/SurfaceCharge.h
	$(CP) $< $@

$(DEST)/SurfaceComp.cxx : $(SRC)/SurfaceComp.cxx
	$(CP) $< $@

$(DEST)/SurfaceComp.h : $(SRC)/SurfaceComp.h
	$(CP) $< $@

$(DEST)/System.cxx : $(SRC)/System.cxx
	$(CP) $< $@

$(DEST)/System.h : $(SRC)/System.h
	$(CP) $< $@

$(DEST)/tally.cpp : $(SRC)/tally.cpp
	$(CP) $< $@

$(DEST)/Temperature.cxx : $(SRC)/Temperature.cxx
	$(CP) $< $@

$(DEST)/Temperature.h : $(SRC)/Temperature.h
	$(CP) $< $@

$(DEST)/tidy.cpp : $(SRC)/tidy.cpp
	$(CP) $< $@

$(DEST)/transport.cpp : $(SRC)/transport.cpp
	$(CP) $< $@

$(DEST)/Use.cpp : $(SRC)/Use.cpp
	$(CP) $< $@

$(DEST)/Use.h : $(SRC)/Use.h
	$(CP) $< $@

$(DEST)/UserPunch.cpp : $(SRC)/UserPunch.cpp
	$(CP) $< $@

$(DEST)/UserPunch.h : $(SRC)/UserPunch.h
	$(CP) $< $@

$(DEST)/utilities.cpp : $(SRC)/utilities.cpp
	$(CP) $< $@

$(DEST)/Utils.cxx : $(SRC)/Utils.cxx
	$(CP) $< $@

$(DEST)/Utils.h : $(SRC)/Utils.h
	$(CP) $< $@

